`include "micro.vh"
module SCPU (
    input clk,
    input rst,
    input MIO_ready,
    input [31:0]Data_in,
    input [31:0]inst_in,
    input IO_break,

    output [3:0]MemRW,
    output CPU_MIO,
    output [31:0]Addr_out,
    output [31:0]PC_out,
    output [31:0]Data_out,

    //debug signals
    output ALUSrc_B,
    output Jump,
    output Branch,
    output RegWrite,
    output JumpSel,
    output BranchSel,
    output PC_RDSel,
    output [31:0]Rs1_data,
    output [31:0] Rs2_data,
    output [31:0]Rd_data,
    output [4:0]Rs1_addr,
    output [4:0]Rs2_addr,
    output [4:0]Rd_addr,
    output [3:0]ALU_Control,
    output [2:0]MemtoReg,
    output [31:0] Reg00, 
    output [31:0] Reg01, 
    output [31:0] Reg02, 
    output [31:0] Reg03, 
    output [31:0] Reg04, 
    output [31:0] Reg05, 
    output [31:0] Reg06, 
    output [31:0] Reg07, 
    output [31:0] Reg08, 
    output [31:0] Reg09, 
    output [31:0] Reg10, 
    output [31:0] Reg11, 
    output [31:0] Reg12, 
    output [31:0] Reg13, 
    output [31:0] Reg14, 
    output [31:0] Reg15, 
    output [31:0] Reg16, 
    output [31:0] Reg17, 
    output [31:0] Reg18, 
    output [31:0] Reg19, 
    output [31:0] Reg20, 
    output [31:0] Reg21, 
    output [31:0] Reg22, 
    output [31:0] Reg23, 
    output [31:0] Reg24, 
    output [31:0] Reg25, 
    output [31:0] Reg26, 
    output [31:0] Reg27, 
    output [31:0] Reg28, 
    output [31:0] Reg29, 
    output [31:0] Reg30, 
    output [31:0] Reg31,
    output [31:0] Data_in_field,

    output csr_w,
    output csr_immsel,
    output ecall,
    output ill_inst,
    output [1:0]csr_opctrl,
    output [31:0]mepc_bypasss_out,
    output [31:0]mscause_bypass_out,
    output [31:0]mtval_bypass_out,
    output [31:0]mtvec_bypass_out,
    output [31:0]mstatus_bypass_out
);
    
    wire MIO_ready,ALUSrc_B,Jump,Branch,RegWrite,JumpSel,BranchSel,PC_RDSel;
    wire ecall,ill_inst,expt_int,csr_w,csr_immsel,mret;
    wire[1:0]    csr_opctrl;
    wire[3:0]    MemRw,Save_base;
    wire[2:0]    ImmSel;
    wire[2:0]    MemtoReg;
    wire[3:0]    ALU_Control;
    wire[2:0]    Mem_dataSel;
    SCPU_ctrl  SCPU_ctrl_U0 (
        .inst_in_ctrl(inst_in),
        .MIO_ready(MIO_ready),
        .ImmSel(ImmSel),
        .ALUSrc_B(ALUSrc_B),
        .MemtoReg(MemtoReg),
        .Jump(Jump),
        .Branch(Branch),
        .RegWrite(RegWrite),
        .MemRW(MemRW),
        .ALU_Control(ALU_Control),
        .JumpSel(JumpSel),
        .BranchSel(BranchSel),
        .CPU_MIO(CPU_MIO),
        .Mem_dataSel(Mem_dataSel),
        .PC_RDSel(PC_RDSel),
        .Save_base(Save_base),
        .IO_break(IO_break),
        .ill_inst(ill_inst),
        .expt_int(expt_int),
        .ecall(ecall),
        .Csr_w(csr_w),
        .Csr_opctrl(csr_opctrl),
        .Csr_immsel(csr_immsel),
        .mret(mret)
    );

    DataPath DataPath_U1(
        .clk(clk),
        .rst(rst),
        .MIO_ready(MIO_ready),
        .inst_in(inst_in),
        .ImmSel(ImmSel),
        .ALUSrc_B(ALUSrc_B),
        .MemtoReg(MemtoReg),
        .Jump(Jump),
        .Branch(Branch),
        .RegWrite(RegWrite),
        .MemRW(MemRW),
        .ALU_Control(ALU_Control),
        .CPU_MIO(CPU_MIO),
        .Data_in(Data_in),
        .JumpSel(JumpSel),
        .BranchSel(BranchSel),
        .ALU_out(Addr_out),
        .Data_out(Data_out),
        .PC_out(PC_out),
        .Mem_dataSel(Mem_dataSel),
        .PC_RDSel(PC_RDSel),
        .Save_base(Save_base),
        .csr_w(csr_w),
        .IO_break(IO_break),
        .csr_opctrl(csr_opctrl),
        .csr_immsel(csr_immsel),
        .mret(mret),

        //debug signals
        .Reg00(Reg00), 
        .Reg01(Reg01), 
        .Reg02(Reg02), 
        .Reg03(Reg03), 
        .Reg04(Reg04), 
        .Reg05(Reg05), 
        .Reg06(Reg06), 
        .Reg07(Reg07), 
        .Reg08(Reg08), 
        .Reg09(Reg09), 
        .Reg10(Reg10), 
        .Reg11(Reg11), 
        .Reg12(Reg12), 
        .Reg13(Reg13), 
        .Reg14(Reg14), 
        .Reg15(Reg15), 
        .Reg16(Reg16), 
        .Reg17(Reg17), 
        .Reg18(Reg18), 
        .Reg19(Reg19), 
        .Reg20(Reg20), 
        .Reg21(Reg21), 
        .Reg22(Reg22), 
        .Reg23(Reg23), 
        .Reg24(Reg24), 
        .Reg25(Reg25), 
        .Reg26(Reg26), 
        .Reg27(Reg27), 
        .Reg28(Reg28), 
        .Reg29(Reg29), 
        .Reg30(Reg30), 
        .Reg31(Reg31),
        .Data_in_field(Data_in_field),
        .Rs1_data(Rs1_data),
        .Rs2_data(Rs2_data),
        .Rs1_addr(Rs1_addr),
        .Rs2_addr(Rs2_addr),
        .Rd_addr(Rd_addr),
        .Rd_data(Rd_data),

        .mepc_bypasss_out(mepc_bypasss_out),
        .mscause_bypass_out(mscause_bypass_out),
        .mtval_bypass_out(mtval_bypass_out),
        .mtvec_bypass_out(mtvec_bypass_out),
        .mstatus_bypass_out(mstatus_bypass_out)
    );

endmodule